### ISSUE TITLE
Most undetected kernel mouse movement on github 

### ISSUE THREAD

**Issue by l1nky-1337** [BuddyBoi/KernelMoveMouse#2]
KeStackAttachProcess going brrrrr 🔥

**Comment by BuddyBoi** [comment]
No offense, but the readme quite literally explains what to do for all the script kiddies that come from those meme cheating / malware forums.

I think you both misunderstand the point of this repo, and what the code is actually doing.
"Detection" aside, this would barely work for constant mouse input anyways.

I also find it ironic that you post your cheating discord, yet your project is an IOCTL driver.
I hope you see the irony there, as again your project is the exact same situation (would never actually be used in a malicious way).

To reiterate, this project doesn't mention nor has anything to do with detection.
